#!/bin/bash
# Lab 6: Conditional Access - Risk-Based Policies
#
# This script demonstrates advanced conditional access:
# 1. Create risk-based MFA requirement
# 2. Create impossible travel detection
# 3. Create policy for managed devices
#
# Time: ~45 minutes
# Prerequisites: Lab 2 (MFA) complete

set -e

echo "=========================================="
echo "Lab 6: Conditional Access Policies"
echo "=========================================="
echo ""

TENANT_ID="your-tenant-id"

echo "Policy 1: Require Strong MFA for Medium Risk Sign-ins"
echo "  Creating policy for sign-ins with medium risk..."
echo ""
echo "  ⚠️  Manual step in Azure Portal:"
echo "    1. Go to: Azure Portal → Entra ID → Security → Conditional Access"
echo "    2. Click 'New policy'"
echo "    3. Configure:"
echo "       Name: 'Require strong MFA for medium risk'"
echo "       Users and groups: All users"
echo "       Cloud apps or actions: All cloud apps"
echo "       Conditions → Sign-in risk: Medium and above"
echo "       Grant: Require FIDO2 security key (if available)"
echo "       Grant: Require authentication strength"
echo "    4. Click 'Create'"
echo ""
read -p "  Press Enter once policy created..."

echo ""
echo "Policy 2: Block Impossible Travel"
echo "  Creating policy for impossible travel..."
echo ""
echo "  ⚠️  Manual step in Azure Portal:"
echo "    1. Go to: Azure Portal → Entra ID → Security → Conditional Access"
echo "    2. Click 'New policy'"
echo "    3. Configure:"
echo "       Name: 'Block impossible travel'"
echo "       Users and groups: All users"
echo "       Cloud apps or actions: All cloud apps"
echo "       Conditions → Other conditions → Unlikely travel"
echo "       Grant: Block access"
echo "    4. Click 'Create'"
echo ""
read -p "  Press Enter once policy created..."

echo ""
echo "Policy 3: Require Managed Device for Sensitive Apps"
echo "  Creating policy for sensitive applications..."
echo ""
echo "  ⚠️  Manual step in Azure Portal:"
echo "    1. Go to: Azure Portal → Entra ID → Security → Conditional Access"
echo "    2. Click 'New policy'"
echo "    3. Configure:"
echo "       Name: 'Require managed device for sensitive apps'"
echo "       Users and groups: All users"
echo "       Cloud apps or actions: Select specific apps (Finance, HR, etc.)"
echo "       Conditions → Device state: Require device to be marked compliant"
echo "       Grant: Require compliant device"
echo "    4. Click 'Create'"
echo ""
read -p "  Press Enter once policy created..."

echo ""
echo "Testing Policies"
echo ""
echo "Test 1: Normal sign-in (low risk)"
echo "  Expected: Sign-in succeeds with password + MFA"
echo "  Steps:"
echo "    1. Go to https://login.microsoft.com"
echo "    2. Sign in with normal credentials + MFA code"
echo ""
read -p "  Did sign-in work? [y/n] "

echo ""
echo "Test 2: Risky sign-in (medium risk)"
echo "  Expected: Requires strong MFA (FIDO2)"
echo "  Steps:"
echo "    1. Use VPN to different country (or simulate unusual location)"
echo "    2. Try to sign in"
echo "    3. Should require FIDO2 key"
echo ""
read -p "  Did stronger auth requirement appear? [y/n] "

echo ""
echo "=========================================="
echo "✅ Lab 6 Complete!"
echo "=========================================="
echo ""
echo "Summary:"
echo "  Policy 1: Medium risk → Require strong MFA"
echo "  Policy 2: Impossible travel → Block"
echo "  Policy 3: Sensitive apps → Require managed device"
echo ""
echo "Policy evaluation order:"
echo "  1. Policies evaluated in order"
echo "  2. All 'Block' policies evaluated first"
echo "  3. 'Grant' policies evaluated after"
echo "  4. If any 'Block' matches → access blocked"
echo ""
echo "Best practices:"
echo "  • Backup global admin account (exempt from policies)"
echo "  • Test in Report-only mode first"
echo "  • Monitor: sign-in logs → Conditional Access"
echo "  • Adjust thresholds based on false positive rate"
echo ""

